export const GlobalStyles = {
  colors: {
    veryLightPrimary: '#bfbfe5',
    lightPrimary: '#aaaadc',
    primary: '#2a2aa8',
    darkPrimary: '#00008B',
    veryLightGray: '#f8f8f8',
    lightGray: '#ededed',
    gray: '#d1d1d1',
    darkGray: '#9f9f9f',
    lightError: '#f0a8a9',
    error: '#ff3333',
    darkError: '#ba1b1d',
    success: '#4bb543',
    warning: '#ffcc00',
    black: '#202020',
    deepBlack: '#000000',
    white: '#ffffff',
    pink: '#fcc4e4',
  },
};
