export const DEFAULT_OPTION_GROUPS = [
  {
    id: '0',
    data: {
      name: 'Size (clothing)',
      optionGroupVariants: ['XXS', 'XS', 'S', 'M', 'L', 'XXL', '3XL', '4XL'],
    },
  },
  {
    id: '1',
    data: {
      name: 'Size (footwear)',
      optionGroupVariants: [
        '32',
        '33',
        '34',
        '35',
        '36',
        '37',
        '38',
        '39',
        '40',
        '41',
        '42',
        '43',
        '44',
        '45',
        '46',
      ],
    },
  },
  {
    id: '2',
    data: {
      name: 'Size (footwear - children)',
      optionGroupVariants: [
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36',
      ],
    },
  },
];
