export const Products = [
  {
    id: '1',
    title: 'С днюхой Клои!',
    imageUri: require('../assets/images/bento1.jpg'),
    category: 'День Рождения',
    price: 5000,
    options: [
      { optionTitle: 'Размер', optionLabels: ['XS', 'S', 'M', 'L', 'XL'] },
      { optionTitle: 'Цвет', optionLabels: ['Белый', 'Черный'] },
    ],
    activeId: '1',
  },
  {
    id: '2',
    title: 'Ведьмы не стареют',
    imageUri: require('../assets/images/bento2.jpg'),
    category: 'Шуточные',
    price: 3500,
    options: [
      { optionTitle: 'Размер', optionLabels: ['XS', 'S', 'M'] },
      { optionTitle: 'Цвет', optionLabels: ['Белый'] },
    ],
    activeId: '1',
  },
  {
    id: '4',
    title: 'Happy Birthday!',
    imageUri: require('../assets/images/bento4.jpg'),
    category: 'День Рождения',
    price: 6200,
    options: [
      { optionTitle: 'Размер', optionLabels: ['XS', 'S'] },
      { optionTitle: 'Цвет', optionLabels: ['Белый'] },
    ],
    activeId: '1',
  },
  {
    id: '5',
    title: 'Стареем вместе',
    imageUri: require('../assets/images/bento5.jpg'),
    category: 'Любимой/Любимому',
    price: 4000,
    options: [
      { optionTitle: 'Размер', optionLabels: ['XS', 'L', 'XL'] },
      { optionTitle: 'Цвет', optionLabels: ['Белый'] },
    ],
    activeId: '1',
  },
  {
    id: '6',
    title: 'Заебан, но не сломлен',
    imageUri: require('../assets/images/bento6.jpg'),
    category: 'Шуточные',
    price: 5000,
    options: [
      { optionTitle: 'Размер', optionLabels: ['XS', 'S', 'M', 'L', 'XL'] },
      { optionTitle: 'Цвет', optionLabels: ['Белый'] },
    ],
    activeId: '1',
  },
  {
    id: '7',
    title: 'HB Teddy',
    imageUri: require('../assets/images/bento7.jpg'),
    category: 'День Рождения',
    price: 4800,
    options: [
      { optionTitle: 'Размер', optionLabels: ['XS'] },
      { optionTitle: 'Цвет', optionLabels: ['Белый'] },
    ],
    activeId: '1',
  },
  {
    id: '3',
    title: 'Любовь',
    imageUri: require('../assets/images/bento3.jpg'),
    category: 'Любимой/Любимому',
    price: 4000,
    options: [
      { optionTitle: 'Размер', optionLabels: ['XS', 'S'] },
      { optionTitle: 'Цвет', optionLabels: ['Белый', 'Черный'] },
    ],
    activeId: '2',
  },
  {
    id: '8',
    title: 'Happy Birthday',
    imageUri: require('../assets/images/bento8.jpg'),
    category: 'День Рождения',
    price: 4000,
    options: [
      { optionTitle: 'Размер', optionLabels: ['XS', 'S', 'M', 'L', 'XL'] },
      { optionTitle: 'Цвет', optionLabels: ['Белый', 'Черный'] },
    ],
    activeId: '1',
  },
  {
    id: '9',
    title: 'Happy Honey',
    imageUri: require('../assets/images/bento9.jpg'),
    category: 'Любимой/Любимому',
    price: 5000,
    options: [
      { optionTitle: 'Размер', optionLabels: ['XS', 'S', 'M'] },
      { optionTitle: 'Цвет', optionLabels: ['Белый', 'Черный', 'Damn'] },
    ],
    activeId: '1',
  },
];
